### PR TITLE
add magento events fired after api call was made

### PR DESCRIPTION
**Pull request by ProxiBlue**
Dispatch magento events after api call was made successfully

### CODE REVIEW

**Comment by dontgitit** [comment]
LGTM, but what's the use case for this?

**Comment by ProxiBlue** [comment]
Hi,

Client sells products on behalf of others. Each product has an email attached via attribute field
Any correspondence that go out, related to products, should send identical correspondence to email assigned to product.

Since the bulk of the emails will be going via iterable, seems logical to hook in there (via events).
Basically, if any product was found, the event will be duplicated after fired to iterable api.

**Comment by dontgitit** [comment]
Hey, sorry, dropped the ball on this. 

Still kind of confused on what this is doing. In the scenario you described, wouldn't you want to fire a second event to Iterable with a different email?

**Comment by ProxiBlue** [comment]
Hi, 

yes, that is what I am achieving, in the least code changes possible.
Without this additional event, I would need to track down every module/code/instance that sends a transactional email, which involves a product.

With the hook in place, I have the ability to inject the "cc'd" emails from on central 'exit point' and any new work/additional module going forward will not need to be adjusted to make sure it also sens a cc.

**Comment by dontgitit** [comment]
Interesting.

If your goal is to set a CC, I think it would be better/nicer to simply select the CC in the email template in Iterable. Is that a possible solution?

**Comment by ProxiBlue** [comment]
No.

Ever product will have a list of cc's
This will normally be one per product, but will be different per product.

The client sells products (furniture) as curators. Each product thus has a
different set of owners.
On 20 Apr 2016 3:15 pm, "dontgitit" notifications@github.com wrote:

Interesting.

If your goal is to set a CC, I think it would be better/nicer to simply
select the CC in the email template in Iterable. Is that a possible
solution?

**Comment by dontgitit** [comment]
I see. You can use handlebars in the CC field though, IIRC. So if your magento product has some field called "emails_to_cc" that looks like "foo@bar.com, baz@test.com", you can just put (for example) `{{shoppingCartItems.[0].emails_to_cc}}` in your template and I _think_ it should work. Give it a try!

**Comment by ProxiBlue** [comment]
If I nee to work on this again, will look at that. As it is, current
solution seems to work, and this is on a contractual basis. So client may
not want to spend more time/money on it, as what they have works.

But good to know going forward :)

[image: proxiblue_document_header.png]

http://www.proxiblue.com.au

Quality, not Quantity!

**Comment by dontgitit** [comment]
Ah, got it. 

The PR LGTM, but I think I'm going to hold off on merging it since I'm not sure anyone else would use this functionality.

**Pull request closed without merging**
