### PR TITLE
Fix filename to match config definition of file, on case sensitive filesystem

### PR DESCRIPTION
**Pull request by ProxiBlue**
In system.xml you defined the source model as: `iterable_trackorderplaced/trackingeventtypes` but the filename was `TrackingEventTypes.php`

In a case sensitive filesystem (linux) this will not work, as magento will try and load a file by name of `Trackingeventtypes.php`

Another (alternative) solution would be to define the source model as `iterable_trackorderplaced/trackingEventTypes` and leave the filename as `TrackingEventTypes.php` but that is not conventional.

### CODE REVIEW

**Comment by dontgitit** [comment]
That makes sense, good catch @ProxiBlue 

Would it be good practice to also rename the class Iterable_TrackOrderPlaced_Model_TrackingEventTypes -> Iterable_TrackOrderPlaced_Model_Trackingeventtypes?

**Comment by ProxiBlue** [comment]
Does not matter. Php is not case sensitive on class names. Leaving that camelcase makes it easier to read.

**Comment by ProxiBlue** [comment]
Note that after some further work with the extension, I find that the chnaged filename causes all the direct class calls to static methods to fail.

Further commits to adjust those calls to conform to the lowercased filename

**Comment by dontgitit** [comment]
Cool, this looks good. I'll merge and try to release a new version this evening.

**Pull request merged**
